api:
  dashboard: true
  debug: false

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web
  file:
    directory: /dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: patrick.schoenfeld@aigentics-germany.de
      storage: /acme.json
      keyType: EC256
      httpChallenge:
        entryPoint: http

log:
  level: INFO

accessLog: {}

serversTransport:
  insecureSkipVerify: true